apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipeline.fullname" . }}
  labels:
    app: {{ include "pipeline.name" . }}
    chart: {{ include "pipeline.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.deploymentLabels }}
{{ toYaml .Values.deploymentLabels | indent 4 }}
    {{- end }}
  annotations:
{{ toYaml .Values.deploymentAnnotations | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "pipeline.name" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      name: {{ include "pipeline.fullname" . }}
      labels:
        app: {{ include "pipeline.name" . }}
        release: "{{ .Release.Name }}"
    annotations:
    {{- if .Values.metrics.enabled  }}
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: {{ .Values.metrics.port | quote }}
    {{- end }}
    {{- if .Values.strategy }}
    strategy:
{{ toYaml .Values.strategy | indent 6 }}
    {{- end }}

    spec:
      initContainers:
      {{- if .Values.mysql.enabled  }}
      - name: check-db-service
        image: busybox
        command: ['sh', '-c', 'until nslookup {{ .Release.Name }}-pipeline-db; do echo waiting for {{ .Release.Name }}-pipeline-db; sleep 1; done;']
      - name: check-db-port
        image: busybox
        command: ['sh', '-c', 'echo STATUS nc -w 2 {{ .Release.Name }}-pipeline-db 3306']
      {{- end }}

      containers:
      {{- if .Values.cloudsql.enabled  }}
      - name: cloudsql-proxy
        image: {{ .Values.cloudsql.image.repository }}:{{ .Values.cloudsql.image.tag }}
        command: ["/cloud_sql_proxy",
                  "-instances={{ .Values.cloudsql.instance }}=tcp:3306"]
      {{- end }}

      - name: pipeline
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: KUBERNETES_RELEASE_NAME
          value: {{ .Release.Name | quote }}
        - name: KUBERNETES_NAMESPACE
          value: {{ .Release.Namespace | quote }}

        - name: PIPELINE_PIPELINE_BASEPATH
          value: {{ .Values.global.pipelineBasepath | quote }}

        - name: PIPELINE_DATABASE_DBNAME
          value: {{ .Values.database.dbname }}
        - name: PIPELINE_DATABASE_ROLE
          value: {{ .Values.database.role }}
        - name: PIPELINE_DATABASE_LOGGING
          value: {{ .Values.database.logging | quote }}
        - name: PIPELINE_DATABASE_AUTOMIGRATEENABLED
          value: {{ .Values.database.autoMigrateEnabled | quote }}

        {{- if .Values.mysql.enabled  }}
        - name: PIPELINE_DATABASE_HOST
          value: {{ .Release.Name }}-pipeline-db
        - name: PIPELINE_DATABASE_DBNAME
          value: {{ default "" .Values.mysql.mysqlDatabase | quote }}
        - name: PIPELINE_DATABASE_USER
          value: {{ default "" .Values.mysql.mysqlUser | quote }}
        - name: PIPELINE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  {{ .Release.Name }}-pipeline-db
              key: mysql-password
        {{- else if .Values.cloudsql.enabled }}
        - name: PIPELINE_DATABASE_HOST
          value: "127.0.0.1"
        - name: PIPELINE_DATABASE_DBNAME
          value: {{ default "" .Values.cloudsql.dbName | quote }}
        - name: PIPELINE_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name:  {{ include "pipeline.fullname" . }}-cloudsql
              key: dbUserName
        - name: PIPELINE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  {{ include "pipeline.fullname" . }}-cloudsql
              key: dbUserPass
        {{- end }}

        - name: PIPELINE_AUTH_CLIENTID
          valueFrom:
            secretKeyRef:
              name: {{ include "pipeline.fullname" . }}
              key: githubClientId
        - name: PIPELINE_AUTH_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "pipeline.fullname" . }}
              key: githubClientSecret
        - name: PIPELINE_AUTH_TOKENSIGNINGKEY
          valueFrom:
            secretKeyRef:
              name: {{ include "pipeline.fullname" . }}
              key: tokenSigningKey
        - name: PIPELINE_GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "pipeline.fullname" . }}
              key: githubToken
        # TODO: the Drone version has to be removed once Pipeline is changed
        - name: PIPELINE_DRONE_URL
          value: http://{{ .Release.Name }}-pipeline-cicd:80
        - name: PIPELINE_CICD_URL
          value: http://{{ .Release.Name }}-pipeline-cicd:80

        - name: VAULT_ADDR
          value: https://{{ .Release.Name }}-vault:8200
        - name: VAULT_CACERT
          value: /vault/tls/ca.crt

        - name: PIPELINE_PIPELINE_BINDADDR
          value: ":{{ .Values.service.internalPort }}"

        {{- if .Values.service.tls }}
        - name: PIPELINE_PIPELINE_CERTFILE
          value: /tls/server.crt
        - name: PIPELINE_PIPELINE_KEYFILE
          value: /tls/server.key
        {{ end }}

        - name: PIPELINE_CERT_SOURCE
          value: {{ .Values.cert.source }}
        - name: PIPELINE_CERT_PATH
          value: {{ .Values.cert.path }}

        {{- if .Values.configuration.anchore.enabled }}
        - name: PIPELINE_ANCHORE_ENDPOINT
          value: {{ default (printf "http://%s-anchore-engine.%s.svc.cluster.local:8228" .Release.Name .Release.Namespace) .Values.anchore.serviceEndpoint | quote }}
        - name: PIPELINE_ANCHORE_ADMINUSER
          value: "admin"
        - name: PIPELINE_ANCHORE_ADMINPASS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-anchore-engine
              key: adminPassword
        {{ end }}

        {{ range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{ end }}

        ports:
        {{- if .Values.metrics.enabled }}
        - containerPort: {{ .Values.metrics.port }}
        {{- end }}
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.global.pipelineBasepath }}/api
            port: {{ .Values.service.internalPort }}
          {{- if .Values.service.tls }}
            scheme: HTTPS
          {{- end }}
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: {{ .Values.global.pipelineBasepath }}/api
            port: {{ .Values.service.internalPort }}
          {{- if .Values.service.tls }}
            scheme: HTTPS
          {{- end }}
          initialDelaySeconds: 10
        resources:
{{ toYaml .Values.resources | indent 12 }}

        volumeMounts:
        - name: config-volume
          mountPath: /root/config/

        - mountPath: /statestore
          name: statestore

        - mountPath: /cache
          name: cache

        - name: vault-tls
          mountPath: /vault/tls
      {{- if .Values.service.tls  }}
        - name: pipeline-tls
          mountPath: /tls
      {{ end }}
      {{- if eq .Values.cert.source "file" }}
        - name: sign-ca
          mountPath: {{ .Values.cert.path }}
      {{ end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "pipeline.fullname" . }}

      - name: cache
        {{- if .Values.cache.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ default (printf "%s-cache" (include "pipeline.fullname" .)) .Values.cache.persistence.existingClaim }}
        {{- else }}
        hostPath:
          path: /opt/pipeline/statestore/cache
        {{- end }}

      - name: statestore
        {{- if .Values.statestore.persistence.enabled }}
        persistentVolumeClaim:
           claimName: {{ default (printf "%s-statestore" (include "pipeline.fullname" .)) .Values.statestore.persistence.existingClaim }}
        {{- else }}
        hostPath:
          path: /opt/pipeline/statestore/
        {{- end }}
      - name: vault-tls
        secret:
          secretName: {{ .Release.Name }}-vault-tls
      {{- if .Values.service.tls  }}
      - name: pipeline-tls
        secret:
          secretName: {{ include "pipeline.fullname" . }}-tls
      {{ end }}
      {{- if eq .Values.cert.source "file" }}
      - name: sign-ca
        secret:
          secretName: {{ include "pipeline.fullname" . }}-sign-ca
      {{ end }}
      serviceAccountName: pipeline
